language: cpp
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: TARGET=linux
    - os: linux
      dist: trusty
      sudo: required
      env: TARGET=win64
    - os: osx
      env: TARGET=osx
  allow_failures:
    - os: osx

cache: ccache

env:
  global:
  - OPENPSTD_MAJOR_VERSION=2
  - OPENPSTD_MINOR_VERSION=1
  - WINTARGET=x86-64-w64-mingw32.shared
  - WINTARGET_PATH=x86_64-w64-mingw32.shared

before_install:
- sudo chmod -R +x build
- export PATH=./build/:$PATH
- export PATH=/opt/qt55/bin/:$PATH
- install_add_repo.sh

install:
- install_glslangValidator.sh
- install_fftw.sh
- install_hdf5.sh
- install_xsltproc.sh
- install_eigen.sh
- install_boost.sh
- install_Qt55.sh

before_script:
- uname -r
- gcc -v
- cmake --version
- cmake --help
- cpack --version
- cpack --help

script:
- compile.sh
- test.sh
- test_shaders.sh

after_success:
- upload_webdav.sh
- appimage.sh
